import streamlit as st
import pandas as pd
import numpy as np
from datetime import datetime
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import MinMaxScaler
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, ForeignKey, text
from sqlalchemy.orm import declarative_base, sessionmaker
from fpdf import FPDF

st.set_page_config(page_title="Bioplastics AI Platform", layout="wide")

# --- DATABASE SETUP ---
Base = declarative_base()

class Formulation(Base):
    __tablename__ = 'formulations'
    id = Column(Integer, primary_key=True)
    batch_code = Column(String)
    agar_percent = Column(Float)
    starch_percent = Column(Float)
    glycerin_percent = Column(Float)
    sorbitol_percent = Column(Float)
    water_percent = Column(Float)

class PropertyTest(Base):
    __tablename__ = 'property_tests'
    id = Column(Integer, primary_key=True)
    formulation_id = Column(Integer, ForeignKey('formulations.id'))
    tensile_strength_mpa = Column(Float)
    elastic_modulus_gpa = Column(Float)
    water_absorption_percent = Column(Float)

# New Table for Historical Export Logging
class ExportLog(Base):
    __tablename__ = 'export_logs'
    id = Column(Integer, primary_key=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    tensile_strength = Column(Float)
    elastic_modulus = Column(Float)
    water_absorption = Column(Float)
    agar_percent = Column(Float)
    starch_percent = Column(Float)
    glycerin_percent = Column(Float)
    sorbitol_percent = Column(Float)
    water_percent = Column(Float)

engine = create_engine('sqlite:///bioplastics.db')

# Auto-create missing tables and upgrade schema
Base.metadata.create_all(engine)

def upgrade_db_schema():
    with engine.connect() as conn:
        for col in ['starch_percent', 'sorbitol_percent']:
            try:
                conn.execute(text(f"ALTER TABLE formulations ADD COLUMN {col} FLOAT DEFAULT 0.0;"))
                conn.commit()
            except Exception:
                pass

upgrade_db_schema()

Session = sessionmaker(bind=engine)

# Helper function to save export entries
def log_recipe_export(tensile, elastic, water_abs, recipe):
    session = Session()
    log_entry = ExportLog(
        tensile_strength=tensile,
        elastic_modulus=elastic,
        water_absorption=water_abs,
        agar_percent=recipe["Agar"],
        starch_percent=recipe["Starch"],
        glycerin_percent=recipe["Glycerin"],
        sorbitol_percent=recipe["Sorbitol"],
        water_percent=recipe["Water / Solvent"]
    )
    session.add(log_entry)
    session.commit()
    session.close()

# --- MODEL TRAINING ---
@st.cache_resource
def load_and_train():
    session = Session()
    query = session.query(Formulation, PropertyTest).join(
        PropertyTest, Formulation.id == PropertyTest.formulation_id
    )
    
    data = []
    for form, test in query.all():
        data.append({
            'agar_percent': form.agar_percent or 0.0,
            'starch_percent': getattr(form, 'starch_percent', 0.0) or 0.0,
            'glycerin_percent': form.glycerin_percent or 0.0,
            'sorbitol_percent': getattr(form, 'sorbitol_percent', 0.0) or 0.0,
            'tensile_strength': test.tensile_strength_mpa,
            'elastic_modulus': test.elastic_modulus_gpa,
            'water_absorption': test.water_absorption_percent
        })
    session.close()
    
    df = pd.DataFrame(data)
    
    X = df[['tensile_strength', 'elastic_modulus', 'water_absorption']].values
    y = df[['agar_percent', 'starch_percent', 'glycerin_percent', 'sorbitol_percent']].values
    
    x_scaler = MinMaxScaler()
    y_scaler = MinMaxScaler()
    
    X_scaled = x_scaler.fit_transform(X)
    y_scaled = y_scaler.fit_transform(y)
    
    model = MLPRegressor(hidden_layer_sizes=(64, 32), max_iter=500, random_state=42)
    model.fit(X_scaled, y_scaled)
    
    return model, x_scaler, y_scaler

model, x_scaler, y_scaler = load_and_train()

# --- PDF GENERATOR HELPER ---
def create_pdf_report(tensile, elastic, water_abs, recipe):
    pdf = FPDF()
    pdf.add_page()
    
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "Bioplastics AI - Formulation Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 5, "Generated by Streamlit Cloud AI Platform", ln=True, align="C")
    pdf.ln(10)
    
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "1. Target Mechanical Properties", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, f"  - Tensile Strength: {tensile:.2f} MPa", ln=True)
    pdf.cell(0, 6, f"  - Elastic Modulus: {elastic:.2f} GPa", ln=True)
    pdf.cell(0, 6, f"  - Water Absorption: {water_abs:.2f} %", ln=True)
    pdf.ln(8)
    
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "2. Predicted Chemical Recipe Ratios", ln=True)
    pdf.set_font("Helvetica", "", 11)
    for component, val in recipe.items():
        pdf.cell(0, 6, f"  - {component}: {val:.2f}%", ln=True)
        
    pdf.ln(12)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 5, "Note: Ratios are predicted using a multi-layer neural network.", ln=True)
    
    return bytes(pdf.output())

# --- APP LAYOUT ---
st.title("🌱 Bioplastics AI Formulation Platform")
st.write("Adjust target properties to generate optimal chemical formulation ratios.")

col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("Target Mechanical Properties")
    tensile = st.slider("Tensile Strength (MPa)", 10.0, 50.0, 30.0, 0.5)
    elastic = st.slider("Elastic Modulus (GPa)", 0.5, 3.5, 2.0, 0.1)
    water_abs = st.slider("Water Absorption (%)", 20.0, 60.0, 40.0, 1.0)

with col2:
    st.subheader("AI Recommended Recipe")
    X_in = x_scaler.transform([[tensile, elastic, water_abs]])
    pred_scaled = model.predict(X_in)
    pred_actual = y_scaler.inverse_transform(pred_scaled)[0]
    
    agar_pct = max(0.0, float(pred_actual[0]))
    starch_pct = max(0.0, float(pred_actual[1]))
    gly_pct = max(0.0, float(pred_actual[2]))
    sorb_pct = max(0.0, float(pred_actual[3]))
    solvent_pct = max(0.0, 100.0 - (agar_pct + starch_pct + gly_pct + sorb_pct))
    
    st.metric("Recommended Agar (%)", f"{agar_pct:.2f}%")
    st.metric("Recommended Starch (%)", f"{starch_pct:.2f}%")
    st.metric("Recommended Glycerin (%)", f"{gly_pct:.2f}%")
    st.metric("Recommended Sorbitol (%)", f"{sorb_pct:.2f}%")
    st.metric("Water / Solvent Balance (%)", f"{solvent_pct:.2f}%")

    recipe_dict = {
        "Agar": agar_pct,
        "Starch": starch_pct,
        "Glycerin": gly_pct,
        "Sorbitol": sorb_pct,
        "Water / Solvent": solvent_pct
    }
    
    pdf_bytes = create_pdf_report(tensile, elastic, water_abs, recipe_dict)
    
    st.write("---")
    
    # Callback on download button click
    if st.download_button(
        label="📄 Download Formulation PDF Report",
        data=pdf_bytes,
        file_name="bioplastic_formulation_report.pdf",
        mime="application/pdf",
        use_container_width=True,
        on_click=log_recipe_export,
        args=(tensile, elastic, water_abs, recipe_dict)
    ):
        st.success("Report downloaded and saved to database history!")

# --- HISTORICAL LOGS DISPLAY ---
with st.expander("📊 View Export History Log"):
    session = Session()
    logs = session.query(ExportLog).order_by(ExportLog.timestamp.desc()).all()
    session.close()
    
    if logs:
        log_data = [{
            "Timestamp (UTC)": log.timestamp.strftime("%Y-%m-%d %H:%M:%S"),
            "Tensile (MPa)": log.tensile_strength,
            "Elastic (GPa)": log.elastic_modulus,
            "Water Abs (%)": log.water_absorption,
            "Agar (%)": f"{log.agar_percent:.2f}",
            "Starch (%)": f"{log.starch_percent:.2f}",
            "Glycerin (%)": f"{log.glycerin_percent:.2f}",
            "Sorbitol (%)": f"{log.sorbitol_percent:.2f}",
            "Solvent (%)": f"{log.water_percent:.2f}"
        } for log in logs]
        st.dataframe(pd.DataFrame(log_data), use_container_width=True)
    else:
        st.info("No exported recipes logged yet.")
