import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.neural_network import MLPRegressor
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime
from sqlalchemy.orm import declarative_base, sessionmaker
from datetime import datetime
from fpdf import FPDF
import streamlit_authenticator as stauth

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="Cloud-Native Bioplastic Formulation AI",
    page_icon="🌱",
    layout="wide"
)

# --- USER AUTHENTICATION SETUP ---
# Convert immutable st.secrets into a mutable dict to allow session writes
credentials = dict(st.secrets['credentials'])

authenticator = stauth.Authenticate(
    credentials,
    st.secrets['cookie']['name'],
    st.secrets['cookie']['key'],
    st.secrets['cookie']['expiry_days']
)

# Render login component in main body
name, authentication_status, username = authenticator.login('main', fields={'Form name': 'Bioplastic AI Platform Login'})

if authentication_status == False:
    st.error('Username/password is incorrect.')
    st.stop()
elif authentication_status == None:
    st.warning('Please log in with your credentials to access team dashboards.')
    st.stop()

# --- DATABASE CONNECTION (SUPABASE POSTGRESQL) ---
@st.cache_resource
def init_db():
    try:
        db_url = st.secrets["postgres"]["url"]
        engine = create_engine(db_url, pool_pre_ping=True)
    except Exception as e:
        st.warning("Cloud DB connection failed or secret missing. Falling back to local SQLite.")
        engine = create_engine("sqlite:///bioplastic_fallback.db")
    return engine

engine = init_db()
Base = declarative_base()

# --- DATABASE ORM MODEL WITH USER ID ---
class ExportLog(Base):
    __tablename__ = 'export_logs'
    id = Column(Integer, primary_key=True)
    user_id = Column(String)  # Tracks owner of the dashboard entry
    project_name = Column(String, default="Unnamed Project")
    timestamp = Column(DateTime, default=datetime.utcnow)
    tensile_strength = Column(Float)
    elastic_modulus = Column(Float)
    water_absorption = Column(Float)
    agar_percent = Column(Float)
    starch_percent = Column(Float)
    glycerin_percent = Column(Float)
    sorbitol_percent = Column(Float)
    water_percent = Column(Float)
    est_cost_per_kg = Column(Float, default=0.0)

Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine)

def log_recipe_export(user_id, project_name, tensile, elastic, water_abs, recipe, cost_per_kg):
    session = Session()
    log_entry = ExportLog(
        user_id=user_id,
        project_name=project_name if project_name.strip() else f"Batch-{datetime.utcnow().strftime('%Y%m%d-%H%M')}",
        tensile_strength=tensile,
        elastic_modulus=elastic,
        water_absorption=water_abs,
        agar_percent=recipe["Agar"],
        starch_percent=recipe["Starch"],
        glycerin_percent=recipe["Glycerin"],
        sorbitol_percent=recipe["Sorbitol"],
        water_percent=recipe["Water / Solvent"],
        est_cost_per_kg=cost_per_kg
    )
    session.add(log_entry)
    session.commit()
    session.close()

# --- TRAIN ML MODEL (MLPRegressor) ---
@st.cache_resource
def train_surrogate_model():
    np.random.seed(42)
    n_samples = 300
    
    agar = np.random.uniform(5, 30, n_samples)
    starch = np.random.uniform(10, 40, n_samples)
    glycerin = np.random.uniform(5, 25, n_samples)
    sorbitol = np.random.uniform(2, 15, n_samples)
    water = 100 - (agar + starch + glycerin + sorbitol)
    
    # Target physical properties
    tensile = 12.0 + 0.8 * agar + 0.5 * starch - 0.6 * glycerin - 0.4 * sorbitol + np.random.normal(0, 1.5, n_samples)
    elastic = 150.0 + 12.0 * agar + 8.0 * starch - 10.0 * glycerin - 6.0 * sorbitol + np.random.normal(0, 15, n_samples)
    water_abs = 40.0 - 0.5 * agar - 0.2 * starch + 1.2 * glycerin + 0.8 * sorbitol + np.random.normal(0, 2.0, n_samples)
    
    X = np.column_stack([agar, starch, glycerin, sorbitol, water])
    y = np.column_stack([tensile, elastic, water_abs])
    
    model = MLPRegressor(hidden_layer_sizes=(64, 32), max_iter=1000, random_state=42)
    model.fit(X, y)
    return model

model = train_surrogate_model()

# --- PDF GENERATOR ---
def generate_pdf_report(user_name, project_name, recipe, tensile, elastic, water_abs, cost_per_kg):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, f"Bioplastic Formulation Report: {project_name}", ln=True, align='C')
    pdf.set_font("Arial", '', 10)
    pdf.cell(0, 8, f"Generated By: {user_name} | Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align='C')
    pdf.ln(10)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 8, "1. Formulation Recipe Components (% w/w):", ln=True)
    pdf.set_font("Arial", '', 11)
    for comp, val in recipe.items():
        pdf.cell(0, 6, f"  - {comp}: {val:.2f}%", ln=True)
    pdf.ln(5)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 8, "2. Predicted Material Properties:", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.cell(0, 6, f"  - Tensile Strength: {tensile:.2f} MPa", ln=True)
    pdf.cell(0, 6, f"  - Elastic Modulus: {elastic:.2f} MPa", ln=True)
    pdf.cell(0, 6, f"  - Water Absorption (24h): {water_abs:.2f}%", ln=True)
    pdf.cell(0, 6, f"  - Estimated Raw Material Cost: ${cost_per_kg:.2f} / kg", ln=True)
    
    return pdf.output(dest='S').encode('latin-1')

# --- SIDEBAR UI ---
st.sidebar.title(f"Welcome, {name} 👋")
authenticator.logout('Logout', 'sidebar')

st.sidebar.header("🧪 Formulation Inputs (% w/w)")
project_name = st.sidebar.text_input("Project / Batch Name", "EcoFilm-Batch-A")

agar = st.sidebar.slider("Agar", 5.0, 30.0, 15.0, 0.5)
starch = st.sidebar.slider("Starch", 10.0, 40.0, 25.0, 0.5)
glycerin = st.sidebar.slider("Glycerin (Plasticizer)", 5.0, 25.0, 12.0, 0.5)
sorbitol = st.sidebar.slider("Sorbitol (Secondary Plasticizer)", 2.0, 15.0, 5.0, 0.5)

water = 100.0 - (agar + starch + glycerin + sorbitol)
if water < 0:
    st.sidebar.error("Warning: Solid components exceed 100%! Reduce values.")
    water = 0.0
else:
    st.sidebar.info(f"Water / Solvent balance: {water:.1f}%")

recipe = {
    "Agar": agar,
    "Starch": starch,
    "Glycerin": glycerin,
    "Sorbitol": sorbitol,
    "Water / Solvent": water
}

# --- PREDICTIONS & COST ---
input_array = np.array([[agar, starch, glycerin, sorbitol, water]])
preds = model.predict(input_array)[0]
tensile_pred, elastic_pred, water_abs_pred = preds[0], preds[1], preds[2]

# Standard raw material cost parameters
costs = {"Agar": 18.0, "Starch": 1.5, "Glycerin": 2.5, "Sorbitol": 3.0, "Water / Solvent": 0.05}
est_cost_per_kg = sum((recipe[k] / 100.0) * costs[k] for k in recipe)

# --- MAIN DASHBOARD INTERFACE ---
st.title("🌱 Cloud-Native Bioplastic Formulation Platform")

col1, col2, col3, col4 = st.columns(4)
col1.metric("Tensile Strength", f"{tensile_pred:.2f} MPa")
col2.metric("Elastic Modulus", f"{elastic_pred:.2f} MPa")
col3.metric("Water Absorption", f"{water_abs_pred:.2f}%")
col4.metric("Est. Cost", f"${est_cost_per_kg:.2f} / kg")

tab1, tab2, tab3 = st.tabs(["📊 Formulation Analysis", "🌐 3D Trade-off Space", "📁 Saved Team Dashboards"])

with tab1:
    st.subheader("Component Breakdown")
    df_recipe = pd.DataFrame(list(recipe.items()), columns=["Component", "Percentage"])
    fig_pie = px.pie(df_recipe, values="Percentage", names="Component", title="Mass Fraction Allocation", hole=0.4)
    st.plotly_chart(fig_pie, use_container_width=True)

with tab2:
    st.subheader("3D Optimization & Property Trade-Offs")
    grid_a = np.linspace(5, 30, 15)
    grid_g = np.linspace(5, 25, 15)
    GA, GG = np.meshgrid(grid_a, grid_g)
    
    Z_tensile = 12.0 + 0.8 * GA + 0.5 * starch - 0.6 * GG - 0.4 * sorbitol
    
    fig_3d = go.Figure(data=[go.Surface(z=Z_tensile, x=GA, y=GG, colorscale='Viridis')])
    fig_3d.update_layout(
        title="Tensile Strength Response Surface (Agar vs Plasticizer)",
        scene=dict(xaxis_title="Agar (%)", yaxis_title="Glycerin (%)", zaxis_title="Tensile (MPa)")
    )
    st.plotly_chart(fig_3d, use_container_width=True)

with tab3:
    st.subheader(f"📁 {name}'s Saved Project Dashboards")
    
    col_dl, col_save = st.columns(2)
    
    # Export PDF Report
    pdf_bytes = generate_pdf_report(name, project_name, recipe, tensile_pred, elastic_pred, water_abs_pred, est_cost_per_kg)
    col_dl.download_button(
        label="📄 Export PDF Technical Report",
        data=pdf_bytes,
        file_name=f"{project_name}_report.pdf",
        mime="application/pdf"
    )
    
    # Save to database
    if col_save.button("💾 Save Current Batch to Supabase"):
        log_recipe_export(username, project_name, tensile_pred, elastic_pred, water_abs_pred, recipe, est_cost_per_kg)
        st.success("Successfully logged batch data to Supabase PostgreSQL!")
    
    st.markdown("---")
    
    # Retrieve user-specific records from Supabase
    session = Session()
    user_logs = session.query(ExportLog).filter(ExportLog.user_id == username).order_by(ExportLog.timestamp.desc()).all()
    session.close()

    if user_logs:
        df_user_logs = pd.DataFrame([{
            "Project / Batch Name": log.project_name,
            "Date": log.timestamp.strftime("%Y-%m-%d %H:%M"),
            "Tensile (MPa)": f"{log.tensile_strength:.2f}",
            "Elastic Modulus (MPa)": f"{log.elastic_modulus:.2f}",
            "Water Abs. (%)": f"{log.water_absorption:.2f}",
            "Est. Cost ($/kg)": f"${log.est_cost_per_kg:.2f}"
        } for log in user_logs])
        
        st.dataframe(df_user_logs, use_container_width=True)
    else:
        st.info("No saved project runs found for your account yet. Use the button above to log your first formulation.")
