[raenest]
researcher_plan_link = "https://app.raenest.com/invoice/payment/RNMJ6E3RC"
enterprise_plan_link = "https://app.raenest.com/invoice/payment/RNM73C35S"
webhook_secret = "raenest_sec_live_biomatx_98234"

[database]
sqlite_path = "bioplastics.db"
